version: '3'

services:

  webapp:
    build: flask/
    ports:
      - "5000:5000"
    depends_on:
      - nginx
    volumes:
      - main_socket:/root/flask

  nginx:
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
      - "587:587"
    volumes:
      - main_socket:/root/flask

volumes:
  main_socket:
